-- Games catalogue. Add more rows any time; users pick from this table when listing.
-- cover_image is optional: paste a public image URL (or a Supabase Storage URL) to show real box art.
insert into public.games (title, platform) values
 ('Marvel''s Spider-Man 2','PS5'),('Marvel''s Spider-Man: Miles Morales','PS5'),('Marvel''s Spider-Man: Miles Morales','PS4'),('Marvel''s Spider-Man','PS4'),
 ('God of War Ragnarök','PS5'),('God of War Ragnarök','PS4'),('God of War','PS4'),
 ('Horizon Forbidden West','PS5'),('Horizon Forbidden West','PS4'),('Horizon Zero Dawn','PS4'),
 ('The Last of Us Part I','PS5'),('The Last of Us Part II','PS4'),('The Last of Us Part II Remastered','PS5'),
 ('Ghost of Tsushima','PS4'),('Ghost of Tsushima Director''s Cut','PS5'),('Ghost of Yōtei','PS5'),
 ('Astro Bot','PS5'),('Ratchet & Clank: Rift Apart','PS5'),('Returnal','PS5'),('Demon''s Souls','PS5'),
 ('Gran Turismo 7','PS5'),('Gran Turismo 7','PS4'),('Uncharted 4: A Thief''s End','PS4'),('Uncharted: Legacy of Thieves Collection','PS5'),
 ('Bloodborne','PS4'),('Death Stranding','PS4'),('Death Stranding Director''s Cut','PS5'),('Days Gone','PS4'),
 ('Grand Theft Auto V','PS4'),('Grand Theft Auto V','PS5'),('Red Dead Redemption 2','PS4'),
 ('EA Sports FC 24','PS4'),('EA Sports FC 24','PS5'),('EA Sports FC 25','PS4'),('EA Sports FC 25','PS5'),
 ('EA Sports FC 26','PS4'),('EA Sports FC 26','PS5'),('FIFA 23','PS4'),('FIFA 23','PS5'),
 ('NBA 2K25','PS4'),('NBA 2K25','PS5'),('NBA 2K26','PS4'),('NBA 2K26','PS5'),
 ('WWE 2K24','PS4'),('WWE 2K24','PS5'),('WWE 2K25','PS4'),('WWE 2K25','PS5'),
 ('UFC 4','PS4'),('UFC 5','PS5'),('Madden NFL 25','PS5'),
 ('Call of Duty: Modern Warfare II','PS4'),('Call of Duty: Modern Warfare II','PS5'),
 ('Call of Duty: Modern Warfare III','PS4'),('Call of Duty: Modern Warfare III','PS5'),
 ('Call of Duty: Black Ops 6','PS4'),('Call of Duty: Black Ops 6','PS5'),
 ('Call of Duty: Black Ops 7','PS4'),('Call of Duty: Black Ops 7','PS5'),
 ('Battlefield 2042','PS4'),('Battlefield 2042','PS5'),('Battlefield 6','PS5'),
 ('Mortal Kombat 11','PS4'),('Mortal Kombat 1','PS5'),('Tekken 8','PS5'),('Street Fighter 6','PS4'),('Street Fighter 6','PS5'),
 ('Assassin''s Creed Valhalla','PS4'),('Assassin''s Creed Valhalla','PS5'),('Assassin''s Creed Mirage','PS4'),('Assassin''s Creed Mirage','PS5'),('Assassin''s Creed Shadows','PS5'),
 ('Far Cry 5','PS4'),('Far Cry 6','PS4'),('Far Cry 6','PS5'),('Watch Dogs: Legion','PS4'),('Watch Dogs: Legion','PS5'),
 ('Cyberpunk 2077','PS4'),('Cyberpunk 2077','PS5'),('The Witcher 3: Wild Hunt Complete Edition','PS4'),('The Witcher 3: Wild Hunt Complete Edition','PS5'),
 ('Elden Ring','PS4'),('Elden Ring','PS5'),('Sekiro: Shadows Die Twice','PS4'),('Dark Souls III','PS4'),
 ('Hogwarts Legacy','PS4'),('Hogwarts Legacy','PS5'),('Diablo IV','PS4'),('Diablo IV','PS5'),
 ('Resident Evil 2','PS4'),('Resident Evil 4','PS4'),('Resident Evil 4','PS5'),('Resident Evil Village','PS4'),('Resident Evil Village','PS5'),
 ('Final Fantasy VII Remake Intergrade','PS5'),('Final Fantasy VII Rebirth','PS5'),('Final Fantasy XVI','PS5'),('Persona 5 Royal','PS4'),
 ('Dragon Ball Z: Kakarot','PS4'),('Dragon Ball Z: Kakarot','PS5'),('Dragon Ball: Sparking! Zero','PS5'),
 ('It Takes Two','PS4'),('It Takes Two','PS5'),('Split Fiction','PS5'),('Minecraft','PS4'),
 ('Need for Speed Heat','PS4'),('Need for Speed Unbound','PS5'),('The Crew Motorfest','PS4'),('The Crew Motorfest','PS5'),
 ('Just Dance 2025 Edition','PS4'),('Just Dance 2025 Edition','PS5'),
 ('Crash Bandicoot N. Sane Trilogy','PS4'),('Spyro Reignited Trilogy','PS4'),
 ('Dying Light 2 Stay Human','PS4'),('Dying Light 2 Stay Human','PS5'),('Monster Hunter: World','PS4'),('Monster Hunter Wilds','PS5'),
 ('Batman: Arkham Knight','PS4'),('Star Wars Jedi: Fallen Order','PS4'),('Star Wars Jedi: Survivor','PS5'),
 ('Mortal Kombat X','PS4'),('Injustice 2','PS4'),('Sackboy: A Big Adventure','PS5'),('Ratchet & Clank','PS4')
on conflict (title, platform) do nothing;
